routes/web.php
<?php
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\UserController;
use App\Http\Controllers\RolController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\ActivityLogController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::middleware('RegisterLog')->group(function () { //Registro de actividad Logs

Route::get('/', function () {
    return view('auth/login');
});

//sesiones
Route::middleware('auth')->group(function() {
    Route::get('sessions', 'App\Http\Controllers\UserController@session')->name('session');
    Route::post('delete-session', 'App\Http\Controllers\UserController@delete');      
});

//spatie
Route::group(['middleware' =>['auth']], function(){
    Route::resource('users', UserController::class);
    Route::resource('roles', RolController::class);
});



Route::middleware(['auth:sanctum', 'verified'])->get('/dash', function () {
    return view('dash.index');
})->name('dash');



//lgoa
Route::resource('logs', 'App\Http\Controllers\ActivityLogController');
Route::get('datatable/logs', 'App\Http\Controllers\ActivityLogController@ajaxAllLogs')
->name('datatable.log'); //https://www.youtube.com/watch?v=Hsw4GGeolmg


}); //cierre log





//plantas



//perifericos
//rutas para almacen B2 periferico




//moviles
//equipos
//imppresoras
//comnent nuevo

app/Http/Controllers/RolController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

//spatie tenemos que traer los modelos de facade los roles y los permisos
use Spatie\Permission\Models\Role;
use Spatie\Permission\Models\Permission;
use Illuminate\Support\Facades\DB;

class RolController extends Controller
{
    function __construct()
    {
        $this->middleware('permission:ver-rol | crear-rol | editar-rol| borrar-rol', ['only'=>['index']]);
        $this->middleware('permission:crear-rol',  ['only'=>['create','store']]);
        $this->middleware('permission:editar-rol', ['only'=>['edit','update']]);
        $this->middleware('permission:borrar-rol', ['only'=>['destroy']]);
    } 


    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    
    public function index()
    {
        $roles = Role::all();
        return view('device.rol.index')->with('roles',$roles);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $permission= Permission::get();
        return view ('device.rol.create', compact('permission'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, ['name'=>'required','permission'=>'required']);
        $role = RoLe::create(['name'=>$request->input('name')]);
        $role->syncPermissions($request->input('permission'));

        return redirect()->route('rol.index');

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $role = RoLe::find($id);
        $permission = Permission::get();
        $rolePermissions = DB::table('role_has_permissions')->where('role_has_permissions.role_id', $id)
         ->pluck('role_has_permissions.permission_id', 'role_has_permissions.permission_id')
         ->all();
         return view('device.rol.edit', compact('role', 'permission', 'rolePermissions'));

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, ['name'=>'required','permission'=>'required']);

        $role = RoLe::find($id);
        $role->name = $request->input('name');
        $role->save();

        $role->syncPermissions($request->input('permission'));
        return redirect()->route('device.rol.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        DB::table('roles')->where('id', $id)->delete();
        return redirect()->route('device.rol.index');
    }
}

resources/views/device/rol/create.blade.php
@extends('adminlte::page')
@section('title', 'Roles')

@section('content')
<section class="section">
    <div class="section-header">
        <h3 class="page_heading">Alta de Roles</h3>
    </div>
    <div class="section-body">
        <div class="row">
            <div class="col-lg-12">
                <div class="card">
                    <div class="card-body">


                        @if ($errors->any())
                        <div class="alert alert-dark alert-dismissible fade show" role="alert">
                            <strong>Revise los campos!</strong>
                            @foreach($errors->all() as $error)
                            <span class="badge badge-danger">{{$error}}</span>
                            @endforeach
                            <button type="button" class="close" data-dismiss="alert" aria-label="close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        @endif

                        {!! Form::open(array('route'=>'roles.store', 'method'=>'POST')) !!}
                        <div class="row">
                            <div class="col-xs-12 col-sm-12 col-md-12">
                                <div class="form-group">
                                    <label for="name">Nombres</label>
                                    {!! Form::text('name', null, array('class'=>'form-control')) !!}
                                </div>

                                <div class="col-xs-12 col-sm-12 col-md-12">
                                    <div class="form-group">
                                        <label for="name">Permisos para este Rol</label>
                                        <br>
                                        <!-- esto nos muestra todo los permisos de la tabla permisos-->
                                        @foreach($permission as $value)
                                        <label>{!! Form::checkbox('permission[]',$value->id, false, array('class'=>'name')) !!}
                                            {{$value->name}} </label>
                                        <br />
                                        @endforeach
                                    </div>

                                </div>

                                <div class="col-xs-12 col-sm-12 col-md-12">
                                    <button type="submit" class="btn btn-primary">Guardar</button>
                                </div>
                            </div>
                        </div>

                        {!! Form::close() !!}



                    </div>
                </div>
            </div>
        </div>
    </div>
    </div>
</section>


@stop

@section('css')
<link rel="stylesheet" href="/css/admin_custom.css">
<link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.2/css/bootstrap.css" rel="stylesheet">
<link href="https://cdn.datatables.net/1.11.4/css/dataTables.bootstrap4.min.css" rel="stylesheet">
<link href="https://cdn.datatables.net/responsive/2.2.9/css/responsive.bootstrap4.min.css" rel="stylesheet">
@stop

@section('js')



<script src="https://code.jquery.com/jquery-3.5.1.js"></script>
<script src="https://cdn.datatables.net/1.11.4/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.11.4/js/dataTables.bootstrap4.min.js"></script>
<script src="https://cdn.datatables.net/responsive/2.2.9/js/dataTables.responsive.min.js"></script>
<script src="https://cdn.datatables.net/responsive/2.2.9/js/responsive.bootstrap4.min.js"></script>
<script>
    $(document).ready(function() {
        $('#roles').DataTable({
            responsive: true,
            autowith: false,
            // "lengthMenu":[[5,10,50, -1],[5,10,50, "All"]]
            "language": {
                "lengthMenu": "Mostrar  " +
                    `<select class="custom-select-sm custom-select-sm form-control form-control-sm">
                          <option value=   '5'>  5</option>
                          <option value=  '10'> 10</option>
                          <option value=  '25'> 25</option>
                          <option value=  '50'> 50</option>
                          <option value= '100'>100</option>
                          <option value=  '-1'>All</option>
                          </select>` +
                    "  Registros por paginas",
                "zeroRecords": "Nada encontrado - disculpas",
                "info": "Mostrando la pagina _PAGE_ de _PAGES_",
                "infoEmpty": "No records available",
                "infoFiltered": "( Filtrado de _MAX_ registros totales)",
                'search': 'Buscar:',
                'paginate': {
                    'next': 'siguiente',
                    'previous': 'anterior'
                }
            }
        });
    });
</script>

@stop

resources/views/device/rol/detail.blade.php
@extends('adminlte::page')

@section('title', 'Roles')

@section('content_header')
<h1>detalle Roles</h1>
@stop

@section('content')

@stop

@section('css')
<link rel="stylesheet" href="/css/admin_custom.css">
<link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.2/css/bootstrap.css" rel="stylesheet">
<link href="https://cdn.datatables.net/1.11.4/css/dataTables.bootstrap4.min.css" rel="stylesheet">
<link href="https://cdn.datatables.net/responsive/2.2.9/css/responsive.bootstrap4.min.css" rel="stylesheet">
@stop

@section('js')



<script src="https://code.jquery.com/jquery-3.5.1.js"></script>
<script src="https://cdn.datatables.net/1.11.4/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.11.4/js/dataTables.bootstrap4.min.js"></script>
<script src="https://cdn.datatables.net/responsive/2.2.9/js/dataTables.responsive.min.js"></script>
<script src="https://cdn.datatables.net/responsive/2.2.9/js/responsive.bootstrap4.min.js"></script>
<script>
    
$(document).ready(function() {
    $('#roles').DataTable({
       responsive:true,
       autowith:false,
      // "lengthMenu":[[5,10,50, -1],[5,10,50, "All"]]
      "language": {
            "lengthMenu": "Mostrar  "  +
                          `<select class="custom-select-sm custom-select-sm form-control form-control-sm">
                          <option value=   '5'>  5</option>
                          <option value=  '10'> 10</option>
                          <option value=  '25'> 25</option>
                          <option value=  '50'> 50</option>
                          <option value= '100'>100</option>
                          <option value=  '-1'>All</option>
                          </select>` +
                          "  Registros por paginas",
            "zeroRecords": "Nada encontrado - disculpas",
            "info": "Mostrando la pagina _PAGE_ de _PAGES_",
            "infoEmpty": "No records available",
            "infoFiltered": "( Filtrado de _MAX_ registros totales)",
            'search': 'Buscar:',
            'paginate':{
                'next':'siguiente',
                'previous':'anterior'
            }
        }
    });
} );
</script>

@stop

resources/views/device/rol/edit.blade.php
@extends('adminlte::page')
@section('title', 'Roles')

@section('content')
<section class="section">
    <div class="section-header">
        <h3 class="page_heading">Editar Roles</h3>
    </div>
    <div class="section-body">
        <div class="row">
            <div class="col-lg-12">
                <div class="card">
                    <div class="card-body">


                        @if ($errors->any())
                        <div class="alert alert-dark alert-dismissible fade show" role="alert">
                            <strong>Revise los campos!</strong>
                            @foreach($errors->all() as $error)
                            <span class="badge badge-danger">{{$error}}</span>
                            @endforeach
                            <button type="button" class="close" data-dismiss="alert" aria-label="close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        @endif

                        {!! Form::model($role, ['method'=>'PATCH','route'=>['roles.update',$role->id]]) !!}
                        <div class="row">
                            <div class="col-xs-12 col-sm-12 col-md-12">
                                <div class="form-group">
                                    <label for="name">Nombre del Rol</label>
                                    {!! Form::text('name', null, array('class'=>'form-control')) !!}
                                </div>

                                <div class="col-xs-12 col-sm-12 col-md-12">
                                    <div class="form-group">
                                        <label for="name">Permisos para este Rol</label>
                                        <br>
                                      
                                        @foreach($permission as $value)
                                 <label>{{ Form::checkbox('permission[]', $value->id, in_array($value->id, $rolePermissions) ? true : false, array('class' => 'name')) }}

    
                                            {{ $value->name }} </label>
                                        <br/>
                                        @endforeach
                                    </div>

                                </div>

                         
                                    <button type="submit" class="btn btn-primary">Guardar</button>
                            
                            </div>
                        </div>

                        {!! Form::close() !!}



                    </div>
                </div>
            </div>
        </div>
    </div>
    </div>
</section>


@stop

@section('css')
<link rel="stylesheet" href="/css/admin_custom.css">
<link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.2/css/bootstrap.css" rel="stylesheet">
<link href="https://cdn.datatables.net/1.11.4/css/dataTables.bootstrap4.min.css" rel="stylesheet">
<link href="https://cdn.datatables.net/responsive/2.2.9/css/responsive.bootstrap4.min.css" rel="stylesheet">
@stop

@section('js')



<script src="https://code.jquery.com/jquery-3.5.1.js"></script>
<script src="https://cdn.datatables.net/1.11.4/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.11.4/js/dataTables.bootstrap4.min.js"></script>
<script src="https://cdn.datatables.net/responsive/2.2.9/js/dataTables.responsive.min.js"></script>
<script src="https://cdn.datatables.net/responsive/2.2.9/js/responsive.bootstrap4.min.js"></script>
<script>
    $(document).ready(function() {
        $('#roles').DataTable({
            responsive: true,
            autowith: false,
            // "lengthMenu":[[5,10,50, -1],[5,10,50, "All"]]
            "language": {
                "lengthMenu": "Mostrar  " +
                    `<select class="custom-select-sm custom-select-sm form-control form-control-sm">
                          <option value=   '5'>  5</option>
                          <option value=  '10'> 10</option>
                          <option value=  '25'> 25</option>
                          <option value=  '50'> 50</option>
                          <option value= '100'>100</option>
                          <option value=  '-1'>All</option>
                          </select>` +
                    "  Registros por paginas",
                "zeroRecords": "Nada encontrado - disculpas",
                "info": "Mostrando la pagina _PAGE_ de _PAGES_",
                "infoEmpty": "No records available",
                "infoFiltered": "( Filtrado de _MAX_ registros totales)",
                'search': 'Buscar:',
                'paginate': {
                    'next': 'siguiente',
                    'previous': 'anterior'
                }
            }
        });
    });
</script>

@stop

resources/views/device/rol/index.blade.php
@extends('adminlte::page')

@section('title', 'Roles')

@section('content_header')
<h1>Listado de Roles</h1>
@stop

@section('content')

@can('crear-rol')
<a href="{{route('roles.create')}}" class="btn btn-primary mb-3">Crear Roles</a>
@endcan


<table id="roles" class="table table-striped">
    <thead>
        <tr>
            <th scope="col">id</th>
            <th scope="col">name</th>        
            <th scope="col">acciones</th>

        </tr>
    </thead>

    <tbody>
        @foreach ($roles as $role)
        <tr>
        <td>{{$role->id}}</td>
          <td>{{$role->name}}</td>
          <td>
            @can('editar-rol')
             <a class="btn btn-primary"  href="{{ route('roles.edit', $role->id)}}"><i class="fa fa-edit" aria-hidden="true"></i></a>
            @endcan
            
             @can('borrar-rol')
             {!! Form::open(['method' => 'DELETE','route' => ['roles.destroy', $role->id],'style'=>'display:inline']) !!}
             {!! Form::button('<i class="fa fa-trash" aria-hidden="true"></i>',['class'=>'btn btn-danger']) !!}
             {!! Form::close() !!}
             @endcan
          </td>

        </tr>
        @endforeach


    </tbody>
</table>
@stop

@section('css')
<link rel="stylesheet" href="/css/admin_custom.css">
<link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.2/css/bootstrap.css" rel="stylesheet">
<link href="https://cdn.datatables.net/1.11.4/css/dataTables.bootstrap4.min.css" rel="stylesheet">
<link href="https://cdn.datatables.net/responsive/2.2.9/css/responsive.bootstrap4.min.css" rel="stylesheet">
@stop

@section('js')



<script src="https://code.jquery.com/jquery-3.5.1.js"></script>
<script src="https://cdn.datatables.net/1.11.4/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.11.4/js/dataTables.bootstrap4.min.js"></script>
<script src="https://cdn.datatables.net/responsive/2.2.9/js/dataTables.responsive.min.js"></script>
<script src="https://cdn.datatables.net/responsive/2.2.9/js/responsive.bootstrap4.min.js"></script>
<script>
    $(document).ready(function() {
        $('#roles').DataTable({
            responsive: true,
            autowith: false,
            // "lengthMenu":[[5,10,50, -1],[5,10,50, "All"]]
            "language": {
                "lengthMenu": "Mostrar  " +
                    `<select class="custom-select-sm custom-select-sm form-control form-control-sm">
                          <option value=   '5'>  5</option>
                          <option value=  '10'> 10</option>
                          <option value=  '25'> 25</option>
                          <option value=  '50'> 50</option>
                          <option value= '100'>100</option>
                          <option value=  '-1'>All</option>
                          </select>` +
                    "  Registros por paginas",
                "zeroRecords": "Nada encontrado - disculpas",
                "info": "Mostrando la pagina _PAGE_ de _PAGES_",
                "infoEmpty": "No records available",
                "infoFiltered": "( Filtrado de _MAX_ registros totales)",
                'search': 'Buscar:',
                'paginate': {
                    'next': 'siguiente',
                    'previous': 'anterior'
                }
            }
        });
    });
</script>

@stop